; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ESP32-S3-TFT-ST7735-128x160]
board = ESP32-S3-TFT-ST7735-128x160
board_build.partitions = custom_littlefs_16MB.csv
build_src_filter =${env.build_src_filter} +<../boards/ESP32-S3-TFT-ST7735-128x160>

build_flags =
	${env.build_flags}
	-Iboards/ESP32-S3-TFT-ST7735-128x160

	-DBOARD_HAS_PSRAM
  	-DUSB_as_HID=1
	-DCORE_DEBUG_LEVEL=1
	-DARDUINO_USB_CDC_ON_BOOT=1  ; Used only in ESP32-S3 to make Serial Comands work

	-DDEVICE_NAME='"ESP32-S3-TFT-ST7735-128x160"'


lib_deps =
	${env.lib_deps}
	xylopyrographer/LiteLED@^3.1.1
